# Generated by Django 4.0.1 on 2022-01-27 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cv_generator', '0002_remove_cv_headline_remove_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cvtranslation',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cv_generator.cv'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cv_generator.projectcategory'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projecttranslation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cv_generator.project'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofiletranslation',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cv_generator.userprofile'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='cvs',
            field=models.ManyToManyField(related_name='work_experiences', to='cv_generator.CV'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workexperiencetranslation',
            name='work_experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cv_generator.workexperience'),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='work_experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cv_generator.workexperience'),
        ),
        migrations.AlterField(
            model_name='worktasktranslation',
            name='work_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cv_generator.worktask'),
        ),
    ]
