# Generated by Django 4.0.1 on 2022-01-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_generator', '0003_alter_cv_user_alter_cvtranslation_cv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttranslation',
            name='name',
        ),
        migrations.AddField(
            model_name='cv',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
