# Generated by Django 4.0.1 on 2022-01-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_generator', '0004_remove_projecttranslation_name_cv_title_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='cvs',
            field=models.ManyToManyField(blank=True, related_name='work_experiences', to='cv_generator.CV'),
        ),
    ]
