# Generated by Django 4.0.1 on 2022-01-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_generator', '0005_alter_workexperience_cvs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='cvs',
        ),
    ]
