# Generated by Django 4.0.1 on 2022-01-28 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cv_generator', '0007_education_educationtask_educationtranslation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationtranslation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='educationtranslation',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='educationtranslation',
            name='start_date',
        ),
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='institution',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
